# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  curso:
    image: curso
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5184:5184
